# Generated by Django 3.2.8 on 2022-06-08 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authuser',
            name='user_type',
            field=models.PositiveSmallIntegerField(choices=[('1', 'Physician'), ('2', 'Patient')], null=True),
        ),
        migrations.AlterField(
            model_name='patientconsultationrecord',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[('Upcoming', 'Upcoming'), ('Done', 'Done')], null=True),
        ),
    ]
