# Generated by Django 4.0.4 on 2022-06-08 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_patientconsultationrecord_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='physician',
            old_name='hospital_affiliations',
            new_name='hospital_affiliation',
        ),
    ]
