# Generated by Django 4.0.4 on 2022-06-09 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20220609_0505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authuser',
            name='user_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Physician'), (2, 'Patient')], null=True),
        ),
        migrations.AlterField(
            model_name='patientconsultationrecord',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[('Done', 'Done'), ('Upcoming', 'Upcoming')], null=True),
        ),
    ]
