# Generated by Django 4.0.4 on 2022-06-08 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_rename_hospital_affiliations_physician_hospital_affiliation'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientconsultationrecord',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[('Done', 'Done'), ('Upcoming', 'Upcoming')], null=True),
        ),
        migrations.AlterField(
            model_name='authuser',
            name='user_type',
            field=models.PositiveSmallIntegerField(choices=[('2', 'Patient'), ('1', 'Physician')], null=True),
        ),
    ]
