# Generated by Django 4.0.4 on 2022-06-09 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_authuser_user_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authuser',
            name='user_type',
            field=models.PositiveSmallIntegerField(choices=[(2, 'Patient'), (1, 'Physician')], null=True),
        ),
        migrations.AlterField(
            model_name='patientconsultationrecord',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[('Upcoming', 'Upcoming'), ('Done', 'Done')], null=True),
        ),
    ]
